import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {bundle} from './build.mjs';
const {testPostgres,pool,ensureCompany,readWorkspace,transaction,applyWorkspaceAction,configurationSchema,reserveAiQuota}=await import(pathToFileURL(await bundle('lib/db/tests/workspace-entry.ts','workspace')).href);
try{
 for(const file of (await readdir(new URL('../migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())await testPostgres.exec(await readFile(new URL(`../migrations/${file}`,import.meta.url),'utf8'));
 await pool.query("INSERT INTO users(google_id,email,name) VALUES('a','a@example.invalid','A'),('b','b@example.invalid','B')");
 const a=await ensureCompany(1),b=await ensureCompany(2);assert.notEqual(a,b);assert.equal(await ensureCompany(1),a);
 const config={companyName:'Teste Advocacia',summary:'Organizar atendimentos e casos.',briefing:{pain:'Pedidos dispersos',intake:'Email',responsibility:'Sócia',financialNeeds:'ambos'},services:['Contratos'],stages:[{id:'analise',label:'Análise'},{id:'entrega',label:'Entrega'}],fields:[{id:'area',label:'Área',type:'select',entity:'demand',required:true,options:['Cível','Contratos']}]};
 assert.equal(configurationSchema.safeParse(config).success,true);
 assert.equal(configurationSchema.safeParse({...config,stages:[config.stages[0],config.stages[0]]}).success,false);
 assert.equal(configurationSchema.safeParse({...config,briefing:undefined}).success,false);
 for(const id of [a,b])await pool.query('UPDATE legal_companies SET configuration=$2 WHERE id=$1',[id,config]);
 const act=(id,type,payload,revision)=>transaction(db=>applyWorkspaceAction(db,id,{type,payload,revision}));
 let state=await act(a,'CREATE_CLIENT',{id:'C-1',name:'Cliente fictício',email:'client@example.invalid',phone:'000'},0);
 assert.equal(state.clients.length,1);assert.equal((await readWorkspace(b)).clients.length,0);
 const demand={id:'D-1',title:'Revisão contratual',client:'Cliente fictício',clientId:'C-1',service:'Contratos',priority:'alta',responsible:'Pessoa Teste',status:'aprovada',dueDate:'2030-10-10',estimatedValue:1000,description:'Teste fictício',origin:'Email',comments:[],history:[],files:[],createdAt:'2030-01-01',customValues:{area:'Contratos'}};
 await assert.rejects(act(a,'CREATE_DEMAND',{...demand,customValues:{}},1),/Preencha/);
 await assert.rejects(act(b,'CREATE_DEMAND',demand,0),/Cliente não pertence/);
 state=await act(a,'CREATE_DEMAND',demand,1);assert.equal(state.demands.length,1);
 await assert.rejects(act(b,'UPDATE_DEMAND',{id:'D-1',updates:{title:'Attack'}},0),/não encontrado/);
 await assert.rejects(act(a,'UPDATE_DEMAND',{id:'D-1',updates:{title:'stale'}},1),/mudaram/);
 state=await act(a,'CONVERT_DEMAND',{demandId:'D-1'},2);const project=state.projects[0];assert.equal(project.budget,1000);assert.equal(project.plannedCost,0);assert.equal(project.demandId,'D-1');assert.equal(state.demands[0].projectId,project.id);
 await assert.rejects(act(a,'CONVERT_DEMAND',{demandId:'D-1'},3),/aprovada/);
 await assert.rejects(act(a,'UPDATE_DEMAND',{id:'D-1',updates:{client:'Troca'}},3),/cliente/);
 state=await act(a,'UPDATE_PROJECT',{id:project.id,updates:{tasks:[{id:'T-1',title:'Revisar contrato',responsible:'Pessoa Teste',done:false,dueDate:'2030-10-01'}]}},3);
 state=await act(a,'TOGGLE_PROJECT_TASK',{projectId:project.id,taskId:'T-1'},4);assert.equal(state.projects[0].progress,100);
 const finance={id:'F-1',projectId:project.id,type:'pagar',description:'Custo teste',clientOrSupplier:'Fornecedor',amount:10.25,dueDate:'2030-10-10',status:'pago',category:'Operação'};
 await assert.rejects(act(b,'CREATE_FINANCIAL',finance,0),/não encontrado/);
 state=await act(a,'CREATE_FINANCIAL',finance,5);assert.equal(state.projects[0].plannedCost,10.25);assert.equal(state.projects[0].realizedCost,10.25);
 state=await act(a,'UPDATE_CLIENT',{id:'C-1',updates:{name:'Cliente renomeado'}},6);assert.equal(state.projects[0].client,'Cliente renomeado');assert.equal(state.demands[0].client,'Cliente renomeado');
 assert.equal((await readWorkspace(a)).financialEntries.length,1);assert.equal((await readWorkspace(b)).projects.length,0);
 await assert.rejects(pool.query('INSERT INTO legal_financial_entries(company_id,id,project_id,amount,type,status,payload) VALUES($1,$2,$3,$4,$5,$6,$7)',[b,'evil',project.id,1,'pagar','pendente',{}]),/foreign key/);
 for(let i=0;i<10;i++)await reserveAiQuota(a,'free');await assert.rejects(reserveAiQuota(a,'free'),/Limite diário/);await reserveAiQuota(a,'pro');await reserveAiQuota(b,'free');
 console.log('PASS: migrations, separate companies, persistent CRUD, custom validation, tenant FKs, stale revisions, atomic conversion, tasks, financial totals, rename consistency, quotas');
}finally{await testPostgres.close();}
