import { z } from 'zod/v4';
import { configurationSchema } from './workspace-validation';
import { generateAi, MANAGEMENT_RULES, type DomusAiResult } from './domus-ai';
const object=(properties:Record<string,unknown>)=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const string={type:'string'};const strings={type:'array',items:string};
const config=object({companyName:string,summary:string,briefing:object({pain:string,intake:string,responsibility:string,financialNeeds:{type:'string',enum:['receber','pagar','ambos','nenhum']}}),services:strings,stages:{type:'array',items:object({id:string,label:string})},fields:{type:'array',items:object({id:string,label:string,type:{type:'string',enum:['text','number','select']},entity:{type:'string',enum:['demand','project']},required:{type:'boolean'},options:strings})}});
const schema=object({reply:string,questions:strings,configuration:{anyOf:[config,{type:'null'}]}});
export const interviewResultSchema=z.object({reply:z.string().min(1).max(4000),questions:z.array(z.string().min(1).max(500)).max(3),configuration:configurationSchema.nullable()});
export async function conductInterview(messages:unknown,onUsage?:(usage:DomusAiResult['usage'])=>Promise<void>){
 const result=await generateAi(MANAGEMENT_RULES+`
Você entrevista um gestor para montar seu sistema, não para cadastrar casos fictícios. Aproveite todas as informações já dadas. Faça no máximo 3 perguntas curtas por rodada, sem repetir respostas. Extraia nome do escritório, áreas/serviços, dor a organizar, entrada de pedidos, etapas de entrega, responsáveis e necessidade de pagamentos/recebimentos. TODOS são essenciais: se faltar qualquer um retorne configuration:null e pergunte; não preencha pendências como se fossem respostas. Pode aceitar 'eu sou responsável', 'não preciso de financeiro' e autorização explícita para sugerir etapas. briefing contém pain (dor), intake (entrada dos pedidos), responsibility (quem acompanha), financialNeeds receber/pagar/ambos/nenhum, somente conforme as respostas. Com todas as respostas, proponha configuration e peça revisão/confirmação. Etapas sugeridas devem ser explicitadas como sugestão no reply. Não invente nomes de equipe, valores, clientes ou informações operacionais afirmadas como fatos. Fora de escritórios de advocacia: explique o escopo e pergunte se deseja continuar para esse segmento.
A configuração deve conter: companyName; summary resumindo problema, entrada, responsabilidade e financeiro; 1 a 12 services; 2 a 8 stages com id simples [a-z0-9_]; até 8 fields. Campos são apenas informações adicionais específicas, não duplique título, cliente, responsável, prazo, prioridade, valor, descrição e status já existentes. Cada field tem id, label, type text/number/select, entity demand/project, required e options (vazio salvo select com 2 ou mais opções). IDs e rótulos não podem se repetir. Evite coletar dados sensíveis desnecessários. Personalização não gera código, integrações bancárias, documentos, automações ou conexões com tribunais. Só apresente essas capacidades como não disponíveis.
Limites obrigatórios: companyName, cada service, cada label e cada option com no máximo 80 caracteres; briefing.pain, briefing.intake e briefing.responsibility com no máximo 150 caracteres cada, em uma frase; summary entre 50 e 600 caracteres; reply com no máximo 1200 caracteres; ids só com letras minúsculas sem acento, dígitos e sublinhado.`,JSON.stringify({messages}),schema,onUsage);
 return {result,parse:()=>interviewResultSchema.parse(JSON.parse(result.text))};
}
